### PR TITLE
WP Smart Contracts Grant Request

### PR DESCRIPTION
**Pull request by WPSmartContracts**
[WP Smart Contracts](https://wpsmartcontracts.com/) introduces a pioneering approach to integrating blockchain technology within WordPress websites. Since its inception in 2019, WP Smart Contracts has provided a robust plugin designed to facilitate the seamless implementation of smart contracts tailored specifically for the WordPress platform.

The plugin simplifies the process of incorporating blockchain functionalities into WordPress environments, offering developers and entrepreneurs a comprehensive suite of tools to deploy and manage various smart contracts with ease. From standard ERC-20/BEP-20 tokens to advanced NFT collections and staking solutions, WP Smart Contracts provides versatile options to address diverse blockchain use cases efficiently.

Website
https://wpsmartcontracts.com/

Grant Proposal
https://wpsmartcontracts.com/grants/WPSC-Darwinia.pdf

### CODE REVIEW

**Comment by wuminzhe** [comment]
@alien315 Will all source code be open source? or just open source part of it?

**Comment by WPSmartContracts** [comment]
> @alien315 Will all source code be open source? or just open source part of it?

Hi @wuminzhe 

Yes, all the code will be open, that is one of the pillars of the proposal.

* Be completely open sources on both the plugins side and the smart contracts side.
* All code will be publicly available in a public repository.
* The deployment will be free, for life, for the Darwinia community

**Comment by wuminzhe** [comment]
> * The deployment will be free, for life, for the Darwinia community

you mean that any one who want to setup these applications listed on your website do not need to pay extra fees for the contracts?

**Comment by wuminzhe** [comment]
sorry for the late reply. We still don’t understand what your WP smart contract is. Can we schedule an online meeting to discuss this further this week? https://calendly.com/d/cpbt-t2n-qyh/one-off-meeting

**Comment by WPSmartContracts** [comment]
Sure, I scheduled the call

Thank you

**Comment by wuminzhe** [comment]
Great product but not fit for darwinia's needs. This PR will be closed, but, hope to see any potential case in the future.

**Pull request closed without merging**
