### PR TITLE
motoDEX proposal

### PR DESCRIPTION
**Pull request by oleksiivinogradov**
Our motoDEX now top 4 game on dAppRadar with 90k UAW

### CODE REVIEW

**Comment by wuminzhe** [comment]
I'll review it.

**Comment by wuminzhe** [comment]
@oleksiivinogradov sorry for being late, we are doing some rebranding work now.

I have reviewed your project. I think it's an on-chain game and marketplace on eos-evm. we feel it is really nice to run it on Darwinia EVM. But I didn't see the source code, will it be open-source?

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov sorry for being late, we are doing some rebranding work now.
> 
> I have reviewed your project. I think it's an on-chain game and marketplace on eos-evm. we feel it is really nice to run it on Darwinia EVM. But I didn't see the source code, will it be open-source?

Yes, we will publish source code after grant will approved and integration will done.

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov We discussed motoDEX.
> 
> 1. We believe that games are not the current narrative for Darwinia. But Darwinia is looking for people to build an NFT marketplace. Are you interested?
> 2. In addition, we hope you can reduce some costs.
> 
> Can you email me(akiwu#itering.io) if you are interested in NFT marketplace.

email sent

**Comment by oleksiivinogradov** [comment]
> @oleksiivinogradov We discussed motoDEX.
> 
> 1. We believe that games are not the current narrative for Darwinia. But Darwinia is looking for people to build an NFT marketplace. Are you interested?
> 2. In addition, we hope you can reduce some costs.
> 
> Can you email me(akiwu#itering.io) if you are interested in NFT marketplace.


Address not found
--
Your message wasn't delivered to akiwu@itering.io because the address couldn't be found, or is unable to receive mail.

Address not found
Your message wasn't delivered to [akiwu@itering.io](mailto:akiwu@itering.io) because the address couldn't be found, or is unable to receive mail.

can u email me alex@openbisea.com ?

**Comment by wuminzhe** [comment]
@oleksiivinogradov email sent.

**Comment by hackfisher** [comment]
Sorry, I have to force push the history, please resubmit you PR if necessary.

https://github.com/oleksiivinogradov/darwinia-collaboration/commit/d662f6bfcf5b112ee6dcb05844179d1266eddfd9

**Pull request closed without merging**
